name: SonarCloud Analysis

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    name: Build and Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Disable shallow clone for better analysis

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || true # Skip failing tests to continue analysis

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token is automatically provided
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Your secret token from SonarCloud
        with:
          args: >
            -Dsonar.projectKey=alaminmohammed8482-max_juice-shop
            -Dsonar.organization=alaminmohammed8482-max
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/test/**
